import streamlit as st
import pandas as pd

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="AI Data Analysis Assistant",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -----------------------------
# CUSTOM CSS
# -----------------------------
st.markdown("""
<style>

.main{
    background:#F5F7FA;
}

.title{
    font-size:42px;
    font-weight:700;
    color:#1E3A8A;
}

.subtitle{
    color:#6B7280;
    font-size:17px;
}

.metric-card{
    background:white;
    padding:20px;
    border-radius:12px;
    box-shadow:0px 2px 12px rgba(0,0,0,.08);
}

.block-container{
    padding-top:2rem;
}

.stButton>button{
    width:100%;
    border-radius:10px;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# HEADER
# -----------------------------

st.markdown(
"""
<div class="title">
📊 AI Data Analysis Assistant
</div>

<div class="subtitle">
Upload a CSV dataset, explore insights, ask AI questions, generate visualizations and export results.
</div>

<br>
""",
unsafe_allow_html=True
)

# -----------------------------
# SIDEBAR
# -----------------------------

st.sidebar.title("⚙ Dashboard")

uploaded_file = st.sidebar.file_uploader(
    "Upload Dataset",
    type=["csv"]
)

chart_type = st.sidebar.selectbox(
    "Chart Type",
    [
        "Bar Chart",
        "Line Chart",
        "Pie Chart"
    ]
)

st.sidebar.markdown("---")

api_key = st.sidebar.text_input(
    "LLM API Key",
    type="password"
)

st.sidebar.button("🚀 Run Analysis")

# -----------------------------
# DATA LOADING
# -----------------------------

if uploaded_file:

    df = pd.read_csv(uploaded_file)

    st.success("Dataset Loaded Successfully")

    # -------------------------
    # METRICS
    # -------------------------

    c1,c2,c3,c4 = st.columns(4)

    c1.metric("Rows", len(df))
    c2.metric("Columns", len(df.columns))
    c3.metric("Missing Values", df.isna().sum().sum())
    c4.metric("Numeric Columns", len(df.select_dtypes("number").columns))

    st.divider()

    # -------------------------
    # DATA PREVIEW
    # -------------------------

    col1,col2 = st.columns([2,1])

    with col1:

        st.subheader("📄 Dataset Preview")

        st.dataframe(
            df,
            use_container_width=True,
            height=400
        )

    with col2:

        st.subheader("ℹ Dataset Info")

        with st.expander("Column Names",True):
            st.write(list(df.columns))

        with st.expander("Data Types"):
            st.dataframe(df.dtypes.astype(str))

        with st.expander("Missing Values"):
            st.dataframe(df.isnull().sum())

    st.divider()

    # -------------------------
    # NATURAL LANGUAGE QUESTIONS
    # -------------------------

    st.subheader("💬 Ask Questions")

    q1 = st.text_input("Question 1")
    q2 = st.text_input("Question 2")
    q3 = st.text_input("Question 3")

    if st.button("Answer Questions"):

        st.info("Connect this button to your LLM or analysis function.")

        if q1:
            st.success(f"Answer:\n\n{q1}")

        if q2:
            st.success(f"Answer:\n\n{q2}")

        if q3:
            st.success(f"Answer:\n\n{q3}")

    st.divider()

    # -------------------------
    # VISUALIZATION
    # -------------------------

    st.subheader("📈 Visualization")

    st.info("Replace this section with your Plotly/Matplotlib chart.")

    chart_placeholder = st.container()

    with chart_placeholder:
        st.empty()

    st.download_button(
        "⬇ Download Chart",
        data=b"",
        file_name="chart.png"
    )

    st.divider()

    # -------------------------
    # AI EXPLANATION
    # -------------------------

    st.subheader("🤖 AI Explanation")

    st.info("""
The explanation generated by your LLM will appear here.

Example:

• Sales increased steadily throughout the year.

• Electronics contributed the largest share.

• Missing values are minimal and unlikely to affect analysis.
""")

    st.divider()

    # -------------------------
    # EXPORT
    # -------------------------

    c1,c2 = st.columns(2)

    with c1:
        st.download_button(
            "📄 Export PDF Report",
            data=b"",
            file_name="analysis_report.pdf"
        )

    with c2:
        st.download_button(
            "📥 Download Summary",
            data=df.describe().to_csv(),
            file_name="summary.csv"
        )

else:

    st.info("⬅ Upload a CSV dataset from the sidebar to begin.")
    